sudo: true
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - MPC_ROOT=/tmp/MPC
    - PINPP_ROOT=$TRAVIS_BUILD_DIR
    - LD_LIBRARY_PATH=$PINPP_ROOT/lib:$LD_LIBRARY_PATH

  matrix:
    - PIN_VERSION=pin-2.14-71313-gcc.4.4.7-linux CPP11=0

before_install:
  # setup C++11 compiler support
  - if [ "$TRAVIS_OS_NAME" == "linux"] && [ "$CXX" == "g++" ] && [ "$CPP11" == "1" ] ; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux"] && [ "$CXX" == "clang++" ] && [ "$CPP" == "1" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update

install:
  # setup required software
  - git clone git://github.com/hilljh82/MPC.git /tmp/MPC
  - wget http://software.intel.com/sites/landingpage/pintool/downloads/$PIN_VERSION.tar.gz -O /tmp/$PIN_VERSION.tar.gz
  - tar -xvf /tmp/$PIN_VERSION.tar.gz -C /tmp
  - export PIN_ROOT=/tmp/$PIN_VERSION

  # C++11 compiler support
  - if [ "$CXX" = "g++" ] && [ "$CPP11" == "1" ]; then sudo apt-get install g++-4.9 && export CXX="g++-4.9" && export CC="gcc-4.9" ; fi
  - if [ "$CXX" == "clang++" ] && [ "$CPP11" == "1" ]; then sudo apt-get install --allow-unauthenticated clang-3.4 && export CXX="clang++-3.4" ; fi

script:
  - $CXX --version
  - perl $MPC_ROOT/mwc.pl -type make -features cpp11=$CPP11,ia32=0,intel64=1 "pin++.mwc"
  - make
