sudo: false
language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    - MPC_ROOT=/tmp/MPC
    - PIN_ROOT=/tmp/pin
    - PINPP_ROOT=$TRAVIS_BUILD_DIR
    - LD_LIBRARY_PATH=$PINPP_ROOT/lib:$LD_LIBRARY_PATH

  matrix:
    - CPP11=0

before_install:
  - git clone git://github.com/DOCGroup/MPC.git /tmp/MPC
  - wget http://software.intel.com/sites/landingpage/pintool/downloads/pin-2.14-71313-gcc.4.4.7-linux.tar.gz -O /tmp/pin.tar.gz
  - tar -xvf /tmp/pin.tar.gz -C /tmp

script:
  - perl $MPC_ROOT/mwc.pl -type make -features cpp11=$CPP11,ia32=0,intel64=1 "pin++.mwc"
  - make
