sudo: false
language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

env:
  global:
    - MPC_ROOT=/tmp/MPC
    - PIN_ROOT=/tmp/$PIN_VERSION
    - PINPP_ROOT=$TRAVIS_BUILD_DIR
    - LD_LIBRARY_PATH=$PINPP_ROOT/lib:$LD_LIBRARY_PATH

  matrix:
    - CPP11=0
    - CPP11=1
    - PIN_VERSION=pin-2.14-71313-gcc.4.4.7-linux
    - PIN_VERSION=pin-2.14-67254-gcc.4.4.7-linux

before_install:
  - git clone git://github.com/DOCGroup/MPC.git /tmp/MPC
  - wget http://software.intel.com/sites/landingpage/pintool/downloads/$PIN_VERSION.tar.gz -O /tmp/$PIN_VERSION.tar.gz
  - tar -xvf /tmp/$PIN_VERSION.tar.gz -C /tmp

script:
  - perl $MPC_ROOT/mwc.pl -type make -features cpp11=$CPP11,ia32=0,intel64=1 "pin++.mwc"
  - make
